#!/usr/bin/env python3
"""Render an N-node Qdrant docker-compose file for self-hosted clusters."""

from __future__ import annotations

import argparse
from pathlib import Path


def _node_service(node: int, image: str) -> str:
    name = f"qdrant_node{node}"
    bootstrap = ""
    if node > 1:
        bootstrap = "\n      - --bootstrap\n      - http://qdrant_node1:6335"

    ports = ""
    if node == 1:
        ports = (
            "\n    ports:\n"
            "      - \"6333:6333\"\n"
            "      - \"6334:6334\"\n"
            "      - \"6335:6335\""
        )

    return (
        f"  {name}:\n"
        f"    image: {image}\n"
        f"    container_name: {name}\n"
        f"    restart: unless-stopped\n"
        f"    command:\n"
        f"      - ./qdrant{bootstrap}\n"
        f"      - --uri\n"
        f"      - http://{name}:6335\n"
        f"    volumes:\n"
        f"      - ./data/{name}:/qdrant/storage"
        f"{ports}\n"
    )


def render_cluster_compose(nodes: int, image: str = "qdrant/qdrant:v1.15.4") -> str:
    if nodes < 1:
        raise ValueError("nodes must be >= 1")

    lines = [
        "# Generated by scripts/render_qdrant_cluster_compose.py",
        "# Usage: docker compose -f docker-compose.yml -f docker-compose.qdrant-cluster.generated.yml up -d",
        "",
        "services:",
    ]

    for i in range(1, nodes + 1):
        lines.append(_node_service(i, image).rstrip())

    lines.extend(
        [
            "",
            "  memories:",
            "    depends_on:",
            "      - qdrant_node1",
            "    environment:",
            "      - QDRANT_URL=http://qdrant_node1:6333",
            f"      - QDRANT_REPLICATION_FACTOR={max(1, nodes)}",
            f"      - QDRANT_WRITE_CONSISTENCY_FACTOR={max(1, min(nodes, (nodes // 2) + 1))}",
            "      - QDRANT_READ_CONSISTENCY=majority",
            "      - QDRANT_WRITE_ORDERING=strong",
            "",
            "  qdrant:",
            "    profiles:",
            "      - disabled",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Render N-node Qdrant cluster compose file")
    parser.add_argument("--nodes", type=int, required=True, help="Number of Qdrant nodes")
    parser.add_argument("--output", type=Path, required=True, help="Output compose path")
    parser.add_argument("--image", default="qdrant/qdrant:v1.15.4", help="Qdrant image")
    args = parser.parse_args()

    rendered = render_cluster_compose(nodes=args.nodes, image=args.image)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output} for {args.nodes} node(s)")


if __name__ == "__main__":
    main()
